title: Killinterview | 面试准备小站
description: 面试准备 再说面试 如何面试 行为面试
url: http://www.saberprince.com
avatar: saberprince.github.io/assets/img/Logo with words.jpg
favicon: saberprince.github.io/assets/img/falcon.jpg
google_analytics: UA-76974711-1
disqus_shortname: saberprince

# Content for about page.
# Each paragraph will be a <p> tag which is inserted to about
# page. text_align is used to align the text. Default is left.
# Other two values are center and right. If there are some links
# in your paragraph, use '?link?' to take the place of a link.
# And then write the real link under links. name is the link
# text. url is the link. when external is set as true, then
# a new whidow will be open when link is clicked.
#
about:
  - paragraph: <img src="/assets/img/avatar.jpg">
    text_align: center

  - paragraph: 作者其人是IT本科出身，毕业后却做了三年管培生。然后飞去了美帝，读了商学院，目前毕业在一家咨询公司工作。居住在美国某大学城。经历算不上离奇，还算丰富多彩。现已游历二十一个国家或地区，喜欢结交朋友。座右铭是：聊天又不会怀孕，不如跟我聊聊呗。
#    text_align: left
 - paragraph: 在美国帮助过一些同学准备面试，擅长辅导行为面试和咨询公司的案例面试。如果你对面试也有些困惑可以看看他写的文章<a class="link-1" href="{{ site.posts[0].url }}">再说面试</a>。

    
